### ISSUE TITLE
How to mod to work with xapix.io?

### ISSUE THREAD

**Issue by pickledolives** [xbill82/backbone-relational-jsonapi#6]
Hi Luca,

I am Oliver from Berlin and have a project serving RESTful jsonapi.org formatted data.

I need to pass an auth_token in the header and would need to set the resource path on each Model.

I am a Rails guy and Backbone noob, could you provide any helpful advice on how to do that, please? Or hint me to a community?

Thank you, Oliver :-)

**Comment by xbill82** [comment]
Hi Oliver,
what do you mean by resource path? Do you need to read a file?
Otherwise, if the `auth_token` is just a string available to you in the scope of the page, you can put it in a cookie (it will be sent with all the requests).
Another way would be to send the token as a GET variable in the urls your models use to make the API calls. For this purpose, you can override the `url` method of the `Backbone.Model` class.
But I suggest you to avoid directly touching the Backbone classes.
I'd rather create my own `AuthModel` that extends `Backbone.Model` (and overrides `url()`) and make all your models extend `AuthModel`.

Hope this is clear enough. Feel free to ask more questions if you need to :smile:

**Comment by pickledolives** [comment]
Hi, wow, this helps a lot already, thx! :)

The "auth_token" needs to be sent in HTTP header of the GET request to my server. Server will use that along with the project name it reads from the URL to auth the request and send a jsonapi response back to the client.

I hope xapix.io users who know more about backbone will follow up on this convo. :) I linked this issue from within my Documentation. If you hate open issues, I can move it there, too, as you like... ;)

Cheers, Oliver

**Comment by xbill82** [comment]
Hi Oliver,
very interesting. Let me give you some more details to help you dig into this problem.

Every time BackboneJS wants to communicate with the server (basically fetching and saving models or collections) it uses `Backbone.sync` which generates the request and passes it to a helper (`Backbone.ajax`) that actually sends it to the server. In the out-of-the-box implementation, `Backbone.ajax` is a simple proxy to [jQuery's `ajax` method](https://api.jquery.com/jquery.ajax/).

If you want to send a custom, app-wide, header in every request, I think the best solution is to override `Backbone.ajax` and force a `headers` field containing your auth_token into the `$.ajax` call.

Just to give you an idea, Backbone's source code looks like

``` javascript
    // Set the default implementation of `Backbone.ajax` to proxy through to `$`.
    // Override this if you'd like to use a different library.
    Backbone.ajax = function() {
      return Backbone.$.ajax.apply(Backbone.$, arguments);
    };
```

This is actually _meant_ to be overridden.

Let me know if it worked for you and, yes, feel fre to redirect the xapix.io guys here :smile:

**Comment by xbill82** [comment]
Hey, I actually tried this, and it works for me.

On application initialization (after Backbone is fully loaded, but before the application is kicked off), I execute this

``` javascript
    Backbone.ajax = function(options) {
        options.headers = _.defaults({"X-Test-Header": "test-value"}, options.headers);
        return Backbone.$.ajax.apply(Backbone.$, [options]);
    }
```

Then I can see the `X-Test-Header` is attached to all the requests.

**Comment by pickledolives** [comment]
Thx! :-)
